16.0 migrate db slitheryduke11 70567
Vauxoo/kate pull request #24
Opened 2023-07-03 20:42 UTC by slitheryduke11

2023-07-05 14:40 UTC, slitheryduke11 commented
Hi, @luisg123v.

I think this is ready. Could you help me, please?

2023-07-10 21:49 UTC, luisg123v requested changes

2023-07-10 21:49 UTC, luisg123v commented on .gitmodules
> +	branch = 16.0
Missing newline at end of file

2023-08-02 16:52 UTC, slitheryduke11 commented
Hi, @luisg123v.

Is this PR alright?

2023-08-02 17:26 UTC, luisg123v commented
Target branch is not correct.

2023-08-02 17:45 UTC, slitheryduke11 commented
> Target branch is not correct.

Done.

2023-08-10 22:55 UTC, merged